#adapted from example in docker documentation
version: '3'

services:
  web:
    build: .
    volumes:
       - .:/code
    ports:
       - 8001:8000
    user: "1000:1004"
    command: python /code/mysite/manage.py runserver 0.0.0.0:8000
